services:
  backend:
    build:
      context: .
    container_name: projetin-backend
    command: >
      /bin/sh -c "python3 manage.py makemigrations &&
                  python3 manage.py migrate &&
                  python3 manage.py iniciar &&
                  python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/projetin
    ports:
      - "8000:8000"  # Expose port 8000 for the backend
    environment:
      - DEBUG=1
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db  # Keep 'db' for internal service communication
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432

volumes:
  postgres_data:
