services:
  backend:
    build:
      context: .
    container_name: backend
    command: >
      /bin/sh -c "python3 manage.py makemigrations &&
                  python3 manage.py migrate &&
                  python3 manage.py iniciar &&
                  python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/projetin
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5433
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
