# Generated by Django 5.0.7 on 2024-08-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('senha', models.TextField()),
            ],
        ),
    ]
