# Generated by Django 5.0.7 on 2024-08-17 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('curriculo', models.TextField(null=True)),
                ('github', models.TextField(null=True)),
                ('linkedin', models.TextField(null=True)),
                ('cra', models.FloatField(null=True)),
                ('senha', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('senha', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('grupo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id_projeto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('descricao', models.TextField()),
                ('dono', models.TextField()),
                ('data_de_criacao', models.BigIntegerField()),
                ('vagas', models.IntegerField()),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.professor')),
            ],
        ),
    ]
